<a href="https://colab.research.google.com/github/CodeHunterOfficial/PythonLibraries/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[Анализ данных](https://www.youtube.com/playlist?list=PLlb7e2G7aSpRb95_Wi7lZ-zA6fOjV3_l7)

[Анализ данных. Часть 2](https://www.youtube.com/playlist?list=PLlb7e2G7aSpRb95_Wi7lZ-zA6fOjV3_l7)

In [1]:
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
import numpy

arr = numpy.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [4]:
a=["Liliya","Ayaz", "Kamilla", "Bulat"]

In [5]:
arrname=np.array(a)
print(arrname)

['Liliya' 'Ayaz' 'Kamilla' 'Bulat']


In [6]:
import numpy as np

print(np.__version__)

1.21.6


In [7]:
print(type(arr))

<class 'numpy.ndarray'>


In [8]:
print(type(arrname))

<class 'numpy.ndarray'>


In [9]:
s=10
print(type(s))

<class 'int'>


In [10]:
import numpy as np

arr = np.array((1, 2, 3, 4, 5))

print(arr)

[1 2 3 4 5]


In [11]:
def swap(a,b):
  b,a=a,b
  return a,b

In [21]:
x=int(input())
y=int(input())
a,b=swap(x,y)

4
7


TypeError: ignored

In [22]:
a=np.array(5)
print(a)

5


In [23]:
ar=np.array([
    [1,2,3],
    [4,5,6]
])
print(ar)

[[1 2 3]
 [4 5 6]]


In [24]:
import numpy as np

arr = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
     ],
       [
           [1, 2, 3], 
           [4, 5, 6]
        ]
        ])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [25]:
print(arr[0])

[[1 2 3]
 [4 5 6]]


In [26]:
print(arr[0][0])

[1 2 3]


In [27]:
print(arr[0][0][0])

1


In [28]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [32]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [41]:
print(arr[0])

[[[[1 2 3 4]]]]


In [37]:
print(arr[0][0])

[[[1 2 3 4]]]


In [33]:
print(arr[0][0][0])

[[1 2 3 4]]


In [34]:
print(arr[0][0][0][0])

[1 2 3 4]


In [35]:
print(arr[0][0][0][0][0])

1


In [36]:
print(arr[0][0][0][0][1])

2


In [43]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8,9,10])

print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [44]:
print(arr[0])

1


In [45]:
print(arr[-1])

10


In [46]:
print(arr[0:4])

[1 2 3 4]


In [47]:
print(arr[0:8:2])

[1 3 5 7]


In [48]:
print(arr[0:8:3])

[1 4 7]


In [49]:
print(arr[-4:])

[ 7  8  9 10]


In [52]:
print(arr[5:])

[ 6  7  8  9 10]


In [53]:
print(arr[-4:-1])

[7 9]


In [54]:
print(arr[-4:-1:-2])

[]


In [55]:
print(arr[-1:-6:-2])

[10  8  6]


In [ ]:
print(arr[-1:-6:-2])

In [56]:
print(arr[-4:])

[ 7  8  9 10]


In [58]:
print(arr[-1:-6:-1])

[10  9  8  7  6]


In [59]:
print(arr[0:4])

[1 2 3 4]


In [61]:
print(arr[-1:-5:-1])

[10  9  8  7]


In [63]:
print(arr[9:5:-1])

[10  9  8  7]


In [65]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [66]:
print(arr[1, 1:4])

[7 8 9]


In [67]:
print(arr[0, 0:3])

[1 2 3]


In [71]:
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [68]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [72]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [74]:
import numpy as np

arr = np.array([1, 0, 1, 0], dtype='b')

print(arr)
print(arr.dtype)

[1 0 1 0]
int8


In [76]:
import numpy as np

arr = np.array([1.81, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [81]:
import numpy as np

arr = np.array([-1.81, 2.1, 3.1, 25874])

newarr = arr.astype('b')

print(newarr)
print(newarr.dtype)

[-1  2  3 18]
int8


In [82]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [83]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [84]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [85]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [86]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [87]:
import numpy as np

arr = np.array([[1, 2, 3], [5, 6, 7, 8]])

print(arr.shape)

(2,)


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  This is separate from the ipykernel package so we can avoid doing imports until


In [89]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [90]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [91]:
newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [95]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

print(arr)

[1 2 3 4 5 6 7 8 9]


In [96]:
newarr = arr.reshape(3, 3)

print(newarr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [97]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [98]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4).base)

[1 2 3 4 5 6 7 8]


In [99]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [100]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


In [108]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8,1, 2, 3, 4, 5, 6,7,8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2 3 4]
  [5 6 7 8]]

 [[1 2 3 4]
  [5 6 7 8]]]


In [109]:
import numpy as np

arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [111]:
for i in range(10):
  print(i, end=' ')

0 1 2 3 4 5 6 7 8 9 

In [113]:
import numpy as np

arr = np.array([11, 2, 301,-58])

for x in arr:
  print(x, end=' ')

11 2 301 -58 

In [117]:
import numpy as np

arr = np.array([12, 2, 3,10,25,-98,14,2])

n=len(arr)
i=0
while i<n:
  print(arr[i], end=' ')
  i=i+1

12 2 3 10 25 -98 14 2 

In [118]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [121]:
for x in arr:
  for i in x:
    print(i, end=' ')
  print()

1 2 3 
4 5 6 


In [122]:
S=0
for x in arr:
  for i in x:
    S=S+i

print(S)

21


In [123]:
import numpy as np

arr = np.array([[5,6,3], [1,2,4], [2,9,7]])
print(arr)

[[5 6 3]
 [1 2 4]
 [2 9 7]]


In [124]:
for x in arr:
  S=0
  for i in x:
    S=S+i
  print(S)

14
7
18


In [125]:
for x in arr:
  mx=x[0]
  for a in x:
    if mx<a:
      mx=a
  print(mx)

6
4
9


In [127]:
import numpy as np

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x, end=' ')

1 2 3 4 5 6 7 8 

In [130]:
import numpy as np

arr = np.array([1.45, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

b'1.45'
b'2.0'
b'3.0'


In [132]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x, end=' ')

1 3 5 7 

In [133]:
import numpy as np

arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [135]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr)
for idx, x in np.ndenumerate(arr):
  print(idx, x)

[[1 2 3 4]
 [5 6 7 8]]
(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [136]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [137]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [138]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [139]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


In [140]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [142]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3]), array([4]), array([5])]


In [143]:
print(newarr[0])

[1 2]


In [144]:
print(newarr[0][0])

1


In [145]:
print(newarr[1][0])

3


In [147]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [148]:
import numpy as np

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [149]:
print(newarr[0])

[[1 2]
 [3 4]]


In [150]:
print(newarr[1])

[[5 6]
 [7 8]]


In [151]:
print(newarr[2])

[[ 9 10]
 [11 12]]


In [152]:
import numpy as np

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10]])]


In [153]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [154]:
print(newarr[0])

[[1 2 3]
 [4 5 6]]


In [155]:
for i in range(3):
  print(newarr[i])
  print()

[[1 2 3]
 [4 5 6]]

[[ 7  8  9]
 [10 11 12]]

[[13 14 15]
 [16 17 18]]



In [161]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], 
                [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [157]:
for i in range(3):
  print(newarr[i])
  print()

[[ 1]
 [ 4]
 [ 7]
 [10]
 [13]
 [16]]

[[ 2]
 [ 5]
 [ 8]
 [11]
 [14]
 [17]]

[[ 3]
 [ 6]
 [ 9]
 [12]
 [15]
 [18]]



In [160]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9],
                [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=0)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [159]:
for i in range(3):
  print(newarr[i])
  print()

[[1 2 3]
 [4 5 6]]

[[ 7  8  9]
 [10 11 12]]

[[13 14 15]
 [16 17 18]]



In [162]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], 
                [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [163]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], 
                [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.vsplit(arr, 3)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [166]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6]),)


In [167]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 3)

print(x)

(array([2]),)


In [168]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7]),)


In [170]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

for i, x in np.ndenumerate(arr):
  if x%2==0:
    print(i, end=' ')


(1,) (3,) (5,) (7,) 

In [171]:
import numpy as np

arr = np.array([1, -2, -3, 4, 5,-6, 7, 8])

x = np.where(arr%2 == 1)

print(x)

(array([0, 2, 4, 6]),)


In [173]:
import numpy as np

arr = np.array([1, -2, -3, 4, 5,-6, 7, 8])

x = np.where(arr<0)

print(x)

(array([1, 2, 5]),)


In [179]:
import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

1


In [181]:
import numpy as np

arr = np.array([6, 7, 8, 9,7,25,78])

x = np.searchsorted(arr, 7, side='right')

print(x)

2


In [183]:
import numpy as np

arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 9])

print(x)

[1 2 4]


In [184]:
import numpy as np

arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [185]:
import numpy as np

arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [186]:
import numpy as np

arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


In [187]:
import numpy as np

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [188]:
import numpy as np

arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


In [189]:
import numpy as np

arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)


[False, False, True, True]
[43 44]


In [190]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is completely divisble by 2, set the value to True, otherwise False
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, True, False, True, False, True, False]
[2 4 6]


In [191]:
import numpy as np

arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [192]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]


In [198]:
from numpy import random

x = random.randint(100)

print(x)

50
